export enum Capability {
  BasicControlCapability = 'BasicControlCapability',
  CarpetModeControlCapability = 'CarpetModeControlCapability',
  CombinedVirtualRestrictionsCapability = 'CombinedVirtualRestrictionsCapability',
  ConsumableMonitoringCapability = 'ConsumableMonitoringCapability',
  DoNotDisturbCapability = 'DoNotDisturbCapability',
  FanSpeedControlCapability = 'FanSpeedControlCapability',
  GoToLocationCapability = 'GoToLocationCapability',
  LocateCapability = 'LocateCapability',
  MapResetCapability = 'MapResetCapability',
  MapSegmentEditCapability = 'MapSegmentEditCapability',
  MapSegmentRenameCapability = 'MapSegmentRenameCapability',
  MapSegmentationCapability = 'MapSegmentationCapability',
  MapSnapshotCapability = 'MapSnapshotCapability',
  PersistentMapControlCapability = 'PersistentMapControlCapability',
  DebugCapability = 'DebugCapability',
  SpeakerTestCapability = 'SpeakerTestCapability',
  SpeakerVolumeControlCapability = 'SpeakerVolumeControlCapability',
  VoicePackManagementCapability = 'VoicePackManagementCapability',
  WaterUsageControlCapability = 'WaterUsageControlCapability',
  WifiConfigurationCapability = 'WifiConfigurationCapability',
  ZoneCleaningCapability = 'ZoneCleaningCapability',
}
